```yaml
   name: Deploy to Vercel

   on:
     push:
       branches:
         - production  # Only deploy on push to 'production' branch
     workflow_dispatch:  # Allows manual deployment

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Deploy API to Vercel
           id: deploy-api
           uses: amondnet/vercel-action@v20
           with:
             vercel-token: ${{ secrets.VERCEL_TOKEN }}
             vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
             vercel-project-id: ${{ secrets.VERCEL_API_PROJECT_ID }}
             working-directory: ./api
             github-comment: false

         - name: Deploy Web to Vercel
           id: deploy-web
           uses: amondnet/vercel-action@v20
           with:
             vercel-token: ${{ secrets.VERCEL_TOKEN }}
             vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
             vercel-project-id: ${{ secrets.VERCEL_WEB_PROJECT_ID }}
             working-directory: ./web
             github-comment: false

         - name: Check Deployment Status
           run: |
             if [ "${{ steps.deploy-api.outputs.vercel-deployment-url }}" == "" ] || [ "${{ steps.deploy-web.outputs.vercel-deployment-url }}" == "" ]; then
               echo "Deployment failed!"
               exit 1
             fi
           env:
             DEPLOY_API_URL: ${{ steps.deploy-api.outputs.vercel-deployment-url }}
             DEPLOY_WEB_URL: ${{ steps.deploy-web.outputs.vercel-deployment-url }}

         - name: Notify Deployment Success
           if: success()
           run: echo "Deployed API to ${{ steps.deploy-api.outputs.vercel-deployment-url }} and Web to ${{ steps.deploy-web.outputs.vercel-deployment-url }}"
   ```